apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-subnet-pool
  namespace: metallb-system
spec:
  addresses: # Campo para informar o range do pool de conexoes do cluster, conforme a faixa de rede interna dos nodes. Dica: Comando `k get node -owide`para verificar range Internal-IP`
  - 172.18.0.240-172.18.0.250 

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: private-subnet-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - private-subnet-pool
